name: Notify on Slack
description: Action to post slack notification from workflow
inputs:
  webhook_url:
    required: true
    description: Slack webhook URL
  title:
    required: true
    description: Message title
  icon:
    required: true
    description: Avatar Icon
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        curl ${{ inputs.webhook_url }} \
        --request POST \
        --header 'Content-type: application/json' \
        --data \
          '{
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "${{ inputs.title }}",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Branch:*\nvk/verify-otp-updates"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Initiated by:*\nthedevvikas vikas.kumar@kredx.com"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Run:*\n#2344"
                  }
                ]
              }
	          ]
          }'
